### ISSUE TITLE
[REQUEST] Dark mode for unattend generator page

### ISSUE THREAD

**Issue by d6hlkgoczv** [cschneegans/unattend-generator#123]
I think it's quite simple and there are browser extensions that do this, but it'd be nice to have a native dark theme in the page since i access it through many computers

**Comment by kzshantonu** [comment]
+1

**Comment by SkyOps117** [comment]
Some CSS I wrote which make a dark theme with the page.
```CSS
:root {
    --background: #000000;
    --foreground: #00ff00;
    --code-color: #00cdff;
}

body {
    margin: 0 !important;
    padding: 0 !important;
}

code {
    color: var(--code-color) !important;
    background: var(--background) !important;
}

* {
    color: var(--foreground) !important;
    background: var(--background) !important;
}
```
![Image](https://github.com/user-attachments/assets/0aef0596-ee21-45a8-95e7-f27a26ba1d08)

I like green text on black background for example.
